#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if is-bool-val-true "${WEB_AUDIO:-0}"; then
    # Audio support enabled.
    echo "/tmp/pulseaudio.cookie"
else
    # Audio support not enabled.  Do not set the variable.
    exit 100
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
