#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if [ "${DARK_MODE:-0}" -eq 1 ]; then
    # Dark mode enabled.
    echo "qt5ct"
else
    # Dark mode *not* enabled.  Do not set the variable.
    exit 100
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
