#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if is-bool-val-true "${DARK_MODE:-0}"; then
    # Dark mode enabled.
    echo "Adwaita-Dark"
else
    # Dark mode *not* enabled.  Do not set the variable.
    exit 100
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
