#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

# Wait for dependent services to be up and running.
s6-waitdeps

echo "[services.d] app: starting "${APP_NAME:-Docker application}"..."
if [ -e /startapp.sh ]; then 
    if [ "${UMASK:-UNSET}" != "UNSET" ]; then
        umask "$UMASK"
    fi
    if [ "${SUP_GROUP_IDS:-UNSET}" != "UNSET" ]; then
        exec 2>&1 $APP_NICE_CMD s6-applyuidgid -u $USER_ID -g $GROUP_ID -G $SUP_GROUP_IDS /startapp.sh
    else
        exec 2>&1 $APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID /startapp.sh
    fi
else
    echo ""
    echo "/!\\ No application to start: /startapp.sh is missing. /!\\"
    echo ""
    # Make sure the container exits with an error code.
    exit 5
fi

# vim: set ft=sh :
