#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

# Make sure openbox is running.
while ! s6-svrunning /var/run/s6/services/openbox 1
do
    echo "[services.d] guiapp: waiting for openbox to be ready..."
    sleep 2
done

echo "[services.d] guiapp: starting "${APP_NAME:-X application}"..."
if [ -e /startapp.sh ]; then 
    exec 2>&1 $APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID /startapp.sh
else
    echo ""
    echo "/!\\ No application to start: /startapp.sh is missing. /!\\"
    echo ""
    # Make sure the container exits with an error code.
    exit 5
fi

# vim: set ft=sh :
