#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

echo "[services.d] xvfb: starting..."
exec 2>&1 /usr/bin/Xvfb $DISPLAY -screen 0 ${DISPLAY_WIDTH}x${DISPLAY_HEIGHT}x24

# vim: set ft=sh :
