#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Prevent background to turn grey when starting fastcompmgr.
hsetroot -solid black

if is-bool-val-false "${CONTAINER_DEBUG:-0}"; then
    exec /opt/base/bin/fastcompmgr "$@" >/dev/null 2>&1
else
    exec /opt/base/bin/fastcompmgr "$@"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
