#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Prevent background to turn grey when starting xcompmgr.
hsetroot -solid black

exec /opt/base/bin/xcompmgr "$@"

# vim:ft=sh:ts=4:sw=4:et:sts=4
