#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if is-bool-val-false "${SECURE_CONNECTION:-0}"; then
    echo "true"
elif [ "${SECURE_CONNECTION_CERTS_CHECK_INTERVAL:-10}" -eq 0 ]; then
    echo "true"
else
    echo "false"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
