#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

TITLE="$1"
MSG="$2"
#LEVEL="$3"

if is-bool-val-true "${WEB_NOTIFICATION:-0}"; then
    exec /opt/base/bin/notify-send "$TITLE" "$MSG"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
