#!/usr/bin/with-contenv sh

#
# Check whether or not openbox is ready.
#

set -u # Treat unset variables as an error.

PSOUT="$(ps -A -o pid,etime,args | grep "/usr/bin/openbox" | grep -vw grep)"

# Not ready if not running.
[ "${PSOUT:-UNSET}" != "UNSET" ] || exit 1

UPTIME_MIN="$(echo "$PSOUT" | tr -s ' ' | cut -d' ' -f3 | cut -d':' -f1)"
UPTIME_SEC="$(echo "$PSOUT" | tr -s ' ' | cut -d' ' -f3 | cut -d':' -f2)"
UPTIME="$(expr $UPTIME_MIN \* 60 + $UPTIME_SEC)"

# Ready if running for more than 2 seconds.
[ "$UPTIME" -gt 2 ]

# vim: set ft=sh :
