#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

# Make sure xvfb is running.
while ! s6-svrunning /var/run/s6/services/xvfb 1
do
    echo "[services.d] openbox: waiting for xvfb to be ready..."
    sleep 2
done

echo "[services.d] openbox: starting..."
exec 2>&1 s6-setuidgid $USER_ID:$GROUP_ID /usr/bin/openbox-session

# vim: set ft=sh :
