#!/bin/sh

set -u # Treat unset variables as an error.

# During its startup, openbox tries to change its workdir to '$HOME'.  Make it
# happy by setting good one.  No data should be written there.
export HOME=/config

exec /usr/bin/openbox-session

# vim:ft=sh:ts=4:sw=4:et:sts=4
