#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

# Wait for dependent services to be up and running.
s6-waitdeps

# During its startup, openbox tries to change its workdir to '$HOME'.  Make it
# happy by setting good one.  No data should be written there.
export HOME=/config

echo "[services.d] openbox: starting..."
exec 2>&1 s6-setuidgid $USER_ID:$GROUP_ID /usr/bin/openbox-session

# vim: set ft=sh :
