#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if is-bool-val-true "${WEB_AUTHENTICATION:-0}" && is-bool-val-true "${SECURE_CONNECTION:-0}"; then
    echo "false"
else
    echo "true"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
