#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

# Make sure xvfb is running.
s6-svok /var/run/s6/services/xvfb || exit 1
UPTIME=$( s6-svstat /var/run/s6/services/xvfb | grep "^up " | cut -d' ' -f4 )
if [ -z "$UPTIME" ] || [ "$UPTIME" -lt 1 ] ; then
    exit 1
fi

# Handle the VNC password.
if [ -f /root/.vncpass ] && [ -n "$( cat /root/.vncpass )" ]; then
    VNC_SECURITY="-rfbauth /root/.vncpass"
else
    VNC_SECURITY="-nopw"
fi

# Handle IPv6 options.
if ifconfig -a | grep -wq inet6; then
    IPV6="-rfbportv6 5900"
else
    IPV6="-rfbportv6 -1 -no6 -noipv6 -httpportv6 -1"
fi

echo "[service.d] x11vnc: starting..."
exec 2>&1 /usr/bin/x11vnc  \
                    -display $DISPLAY \
                    -rfbport 5900 \
                    $IPV6 \
                    -forever \
                    -desktop "${APP_NAME}" \
                    -cursor arrow \
                    -shared \
                    -httpdir /opt/novnc/ \
                    $VNC_SECURITY

# vim: set ft=sh :
